### PR TITLE
Error tooltips and logging 🤕 

### LINKED ISSUE #7: error handling when custom overlays fail
When an overlay is loaded, and throws some exception or fails to load cleanly we should better handle that error.

### PR DESCRIPTION
**Pull request by bengreenier**
This adds all those fancy debugging and safety features you've been looking for! ✨ 

+ Handle plugins that fail to load (`require('./path/to/plugin')` fails)
+ Handle plugins that fail to render (`React.createElement(Plugin)` fails)
+ Log critical events
+ Default log level to `verbose` when `NODE_ENV !== 'production'`
+ fixes #7 

The logging uses [electron-log](https://www.npmjs.com/package/electron-log) which writes to:

    on Linux: ~/.config/<app name>/log.log
    on OS X: ~/Library/Logs/<app name>/log.log
    on Windows: %USERPROFILE%\AppData\Roaming\<app name>\log.log

Plugin failures are communicated using the [Tray.displayBalloon()](https://electronjs.org/docs/api/tray#traydisplayballoonoptions-windows) electron api, as well as being written to the log.

Examples:

```
showing tooltip Plugin Render Error
[2018-10-02 10:52:38.229] [error] Failed to render clock located at V:\vs_workspace\overlayed\dist\app\plugin\Clock

showing tooltip Plugin Load Error
[2018-10-02 10:46:26.621] [error] Failed to load clock from V:\vs_workspace\overlayed\dist\app\plugin\Clock
```

### CODE REVIEW

File: src/app/helpers/serialization.tsx [hunk 1]
```diff
@@ -114,9 +117,23 @@ const loadPlugins = (dir : string, rootSettings : any) => {
         component: componentPath
       }} as IInstallNeededPlugin
     } else {
-      return {...plugin, ...{
-        component: require(componentPath).default as React.ComponentType<any>
-      }} as IInstalledPlugin
+      try {
+        return {...plugin, ...{
```
Comment (Ethan-Arrowood) [inline src/app/helpers/serialization.tsx]: You can rewrite this to:

```javascript
return {
  ...plugin,
  component: require(componentPath).default as React.ComponentType<any>
} as IInstalledPlugin
```

File: src/app/main/ErrorBoundry.tsx [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+export class ErrorBoundary extends React.Component<{onError: (err : Error) => void}, {hasError: boolean}> {
+  constructor(props : any) {
+    super(props)
+    this.state = { hasError: false }
+  }
+
+  public componentDidCatch(error : Error) {
+    this.setState({ hasError: true })
+    this.props.onError(error)
```
Comment (Ethan-Arrowood) [inline src/app/main/ErrorBoundry.tsx]: Is this onError function dependent on state in anyway? If so you should consider moving line 11 into a callback function of the `setState` method on line 10.

File: src/app/main/Plugin.tsx [hunk 3]
```diff
@@ -20,6 +24,7 @@ export class Plugin extends React.Component<IPluginProps, any> {
     super(props)
 
     this.onLabelLinkClicked = this.onLabelLinkClicked.bind(this)
+    this.onError = this.onError.bind(this)
```
Comment (Ethan-Arrowood) [inline src/app/main/Plugin.tsx]: To avoid binding the component `this` you can declare your onError method differently. See how I do it [here](https://github.com/Ethan-Arrowood/camper-tracking-app/blob/2c69f92fcd3a6116c9c2ebab1a7ead68a9150817/client/src/pages/CamperList/CamperList.js#L37-L43)

Also check out the next comment on the `onError` function where I show you the proper rewrite.

File: src/app/main/Plugin.tsx [hunk 4]
```diff
@@ -42,8 +49,20 @@ export class Plugin extends React.Component<IPluginProps, any> {
     if (e.target) {
       const uri = (e.target as HTMLElement).getAttribute('data-open')
       if (uri) {
+        log.info(`plugin label clicked: opening ${uri}`)
         open(uri)
       }
     }
   }
+
+  private onError(err : Error) {
```
Comment (Ethan-Arrowood) [inline src/app/main/Plugin.tsx]: rewrite to 
```javascript
private onError = (err : Error) => { ... }
```

File: src/app/main/PluginGrid.tsx [hunk 5]
```diff
@@ -107,21 +110,27 @@ export class PluginGrid extends React.Component<IPluginGridProps, IState> {
...
+    log.info(`starting install for [${installNeeded.map(e => e.name).join(',')}]`)
+
     // install the uninstalled plugins
     Promise.all(this.installPlugins(installNeeded)).then((installedPlugins) => {
       // when these load, merge them in
       this.setState({
         plugins: this.state.plugins.concat(installedPlugins)
       })
+    }, (error) => {
+      log.error(`failed installation: ${error}`)
```
Comment (Ethan-Arrowood) [inline src/app/main/PluginGrid.tsx]: if `error` is an object it may be printed like so: `failed installation: [object Object]`
if it is an instance of `Error` then it will print like so: `failed installation: Error: <message>`

I recommend using `error.message` when logging errors through template strings

File: src/app/main/PluginGrid.tsx [hunk 6]
```diff
@@ -143,9 +152,20 @@ export class PluginGrid extends React.Component<IPluginGridProps, IState> {
         }, (err) => {
           // if we error, fail out, otherwise resolve to an IInstalledPlugin
           if (err) { reject(err) }
-          resolve({...plugin, ...{
-            component: require(plugin.component).default as React.ComponentType<any>
-          }} as IInstalledPlugin)
+          try {
+            resolve({...plugin, ...{
```
Comment (Ethan-Arrowood) [inline src/app/main/PluginGrid.tsx]: see above comment on better obj destructuring

File: src/electron/Bootstrap.ts [hunk 7]
```diff
@@ -0,0 +1,146 @@
+import { app, ipcMain, Menu, MenuItem, nativeImage, Tray } from "electron"
+import log from 'electron-log'
```
Comment (Ethan-Arrowood) [inline src/electron/Bootstrap.ts]: inconsistent quote characters. Surprised linter didn't yell at you for this.

File: src/electron/CompositeWindow.ts [hunk 8]
```diff
@@ -30,12 +31,14 @@ export class CompositeWindow extends BrowserWindow {
 
     // notify react side
     this.webContents.send(IPCMessageNames.ToggleEditMode, this.isInteractive)
+    log('toggled compositor interactivity')
```
Comment (Ethan-Arrowood) [inline src/electron/CompositeWindow.ts]: Throughout the previous code you are using `log.info` or `log.error`; why nothing here?

Comment (bengreenier) [reply src/electron/CompositeWindow.ts]: good catch

File: src/app/helpers/serialization.tsx (hunk 1 above)
Comment (bengreenier) [reply src/app/helpers/serialization.tsx]: this is cool - i'm going to punt on this for now though, as there's quite a few places in the codebase that do this that deserve to be refactored at the same time. see https://github.com/bengreenier/overlayed/issues/36

File: src/app/main/ErrorBoundry.tsx (hunk 2 above)
Comment (bengreenier) [reply src/app/main/ErrorBoundry.tsx]: not dependent, as such keeping as is for now

File: src/app/main/Plugin.tsx (hunk 3 above)
Comment (bengreenier) [reply src/app/main/Plugin.tsx]: makes sense, but punting for now as it requires a larger change across the codebase for consistency: https://github.com/bengreenier/overlayed/issues/37

File: src/app/main/PluginGrid.tsx (hunk 5 above)
Comment (bengreenier) [reply src/app/main/PluginGrid.tsx]: would prefer to refactor template content to expect Error: message than rely on a specific object shape here. will make the change - good catch!

File: src/electron/Bootstrap.ts (hunk 7 above)
Comment (bengreenier) [reply src/electron/Bootstrap.ts]: same.

File: src/app/main/PluginGrid.tsx (hunk 5 above)
Comment (Ethan-Arrowood) [reply src/app/main/PluginGrid.tsx]: this looks like the only outstanding comment then its good to merge ✨
